[package]
name = "my-site-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.219", features = ["derive"] }
database = { version = "0.1.0", path = "database" }
time = "0.3.41"
